import { Poppins } from "next/font/google";
import "./globals.css";
import Header from "@/components/common/Header";

// Correct usage of Poppins font
const font = Poppins({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"], // Use `weight` (singular)
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={font.className}>
      <body className="antialiased">
        <Header />
        {children}
      </body>
    </html>
  );
}
